# FinBrain Project - finbrain-secretprovider.yaml - MIT License (c) 2025 Nadav Eshed


apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: finbrain-secrets-provider # The name of this SecretProviderClass object 
  namespace: default # Namespace where my Flask app runs

spec:
  provider: aws # Tells Kubernetes we're using AWS as the cloud provider for secrets

  parameters:
    objects: | # "objects" defines which secrets to fetch and how
      - objectName: "finbrain-secrets" # Name of the secret as it appears in AWS Secrets Manager
        objectType: "secretsmanager" # Specifies that it's stored in Secrets Manager 

        # jmesPath lets me extract specific keys from the secret JSON and give them friendly names
        jmesPath:
          - path: MONGO_URI # The key name inside the AWS secret (case-sensitive)
            objectAlias: mongo_uri # The name of the file that will be created inside the pod
          - path: REDIS_URL # Another key inside the same secret
            objectAlias: redis_url # Will also become a file name inside the pod