name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub 
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

  tests:
    runs-on: ubuntu-latest
    needs: docker-login  

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set up test environment
        env:
          TEST_MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
        run: |
          echo "ENV=test" >> $GITHUB_ENV
          echo "MONGO_URI=$TEST_MONGO_URI" >> $GITHUB_ENV
          echo "REDIS_URL=redis://localhost:6379/0" >> $GITHUB_ENV

      - name: Run all tests
        env:
          PYTHONPATH: ${{ github.workspace }}/server:${{ github.workspace }}/server/src
        run: |
          cd server
          python -m pytest -v
